name: base
channels:
  - rapidsai-nightly
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy=1.23
  - deprecation
  - click 
  - imageio 
  - ncempy
  - h5py=3.6
  - ipykernel
  - ipympl
  - matplotlib
  - jupyterlab
  - cudatoolkit=11.7 
  - dask=2022.11
  - distributed
  - dask-cuda 
  - pytest
  - numba
  - ucx-proc=*=gpu
  - ucx
  - ucx-py
  - rmm
  - cupy
  - pip:
    - pyzmq