name: cuda

on:
  push:
    branches:
      - "dask-cupy"

jobs:
  # Builds base image for stempy of various verions if Dockerfile.base has changed
  build-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: stempy-cuda

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build/push Dockerfile
        uses: docker/build-push-action@v3
        with:
          context: ./docker/${{ matrix.version }}
          file: ./docker/${{ matrix.version }}/Dockerfile
          load: true
          target: base
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.version }}-base:latest
          cache-to: type=gha
          cache-from: type=gha,mode=max
      -
        name: Build/push Dockerfile
        uses: docker/build-push-action@v3
        with:
          context: ./docker/${{ matrix.version }}
          file: ./docker/${{ matrix.version }}/Dockerfile
          push: true
          target: stempy
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.version }}:latest
          cache-from: type=gha,mode=max