name: docker

on:
  push:
    branches:
      - "master"
      - "update-dockerfile2"

jobs:
  # Builds base image for stempy (no cuda) if Dockerfile.base has changed
  Build-base:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Determine if Dockerfile.base changed
        id: changed-dockerfile-base
        uses: tj-actions/changed-files@v35
        with:
          files: |
            docker/Dockerfile.base
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build/push Dockerfile.base
        uses: docker/build-push-action@v3
        if: ${{ contains(github.event.head_commit.message, 'trigger-ci') || steps.changed-dockerfile-base.outputs.any_changed == 'true'}}
        with:
          context: ./docker
          file: ./docker/Dockerfile.base
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stempy-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

# Builds stempy every time after Build-base is done
  Build-stempy:
    runs-on: ubuntu-latest
    needs: [Build-base]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Determine if Dockerfile.stempy changed
        id: changed-dockerfile-stempy
        uses: tj-actions/changed-files@v35
        with:
          files: |
            docker/Dockerfile.stempy
      -
        name: Determine if Dockerfile.base changed
        id: changed-dockerfile-base
        uses: tj-actions/changed-files@v35
        with:
          files: |
            docker/Dockerfile.base
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build/push Dockerfile.stempy
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          file: ./docker/Dockerfile.stempy
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stempy:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Tests stempy-cuda
  test-stempy:
    runs-on: ubuntu-latest
    needs: [Build-stempy]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build/push Dockerfile.stempy-test
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          file: ./docker/Dockerfile.stempy-test
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stempy-test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Builds base image for stempy (with cuda/dask) if Dockerfile.base-cuda has changed
  Build-base-cuda:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Determine if Dockerfile.base-cuda changed
        id: changed-dockerfile-base-cuda
        uses: tj-actions/changed-files@v35
        with:
          files: |
            docker/Dockerfile.base-cuda
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build/push Dockerfile.base-cuda
        uses: docker/build-push-action@v3
        if: ${{ contains(github.event.head_commit.message, 'trigger-ci') || steps.changed-dockerfile-base-cuda.outputs.any_changed == 'true'}}
        with:
          context: ./docker
          file: ./docker/Dockerfile.base-cuda
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stempy-base-cuda:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Builds stempy-cuda every time after Build-base-cuda is done
  Build-stempy-cuda:
    runs-on: ubuntu-latest
    needs: [Build-base-cuda]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build/push Dockerfile.stempy-cuda
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          file: ./docker/Dockerfile.stempy-cuda
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stempy-cuda:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # test-stempy-cuda:
  #   runs-on: ubuntu-latest
  #   needs: [Build-stempy-cuda]
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     -
  #       name: Build/push Dockerfile.stempy-cuda
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: ./docker
  #         file: ./docker/Dockerfile.stempy-cuda
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/stempy-cuda-test:latest
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max