name: docker

on:
  push:
    branches:
      - "master"

jobs:
  # Builds base image for stempy (no cuda) if Dockerfile.base has changed
  Build-base:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Determine if Dockerfile.base changed
        id: changed-dockerfile-base
        uses: tj-actions/changed-files@v35
        with:
          files: |
            docker/Dockerfile.base
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build/push Dockerfile.base
        uses: docker/build-push-action@v3
        if: ${{ contains(github.event.head_commit.message, 'trigger-ci') || steps.changed-dockerfile-base.outputs.any_changed == 'true'}}
        with:
          context: ./docker
          file: ./docker/Dockerfile.base
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stempy-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

# Builds stempy every time after Build-base is done
  Build-stempy:
    runs-on: ubuntu-latest
    needs: [Build-base]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Determine if Dockerfile.stempy changed
        id: changed-dockerfile-stempy
        uses: tj-actions/changed-files@v35
        with:
          files: |
            docker/Dockerfile.stempy
      -
        name: Determine if Dockerfile.base changed
        id: changed-dockerfile-base
        uses: tj-actions/changed-files@v35
        with:
          files: |
            docker/Dockerfile.base
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build/push Dockerfile.stempy
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          file: ./docker/Dockerfile.stempy
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stempy:latest
          cache-from: type=gha
      -
        name: Export locally
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          file: ./docker/Dockerfile.stempy-test
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stempy-test:latest
          outputs: type=docker,dest=/tmp/stempy-test.tar

      - 
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: stempy-test
          path: /tmp/stempy-test.tar
          retention-days: 1

  # Tests stempy-cuda
  test-stempy:
    runs-on: ubuntu-latest
    needs: [Build-stempy]
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: stempy-test
          path: /tmp
      -
        name: Load image and run tests
        run: |
          docker load --input /tmp/stempy-test.tar
          docker run ${{ secrets.DOCKERHUB_USERNAME }}/stempy-test:latest /bin/bash
          conda activate stempy
          cd /test
          pytest tests

  # Builds base image for stempy (with cuda/dask) if Dockerfile.base-cuda has changed
  Build-base-cuda:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Determine if Dockerfile.base-cuda changed
        id: changed-dockerfile-base-cuda
        uses: tj-actions/changed-files@v35
        with:
          files: |
            docker/Dockerfile.base-cuda
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build/push Dockerfile.base-cuda
        uses: docker/build-push-action@v3
        if: ${{ contains(github.event.head_commit.message, 'trigger-ci') || steps.changed-dockerfile-base-cuda.outputs.any_changed == 'true'}}
        with:
          context: ./docker
          file: ./docker/Dockerfile.base-cuda
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stempy-base-cuda:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Builds stempy-cuda every time after Build-base-cuda is done
  Build-stempy-cuda:
    runs-on: ubuntu-latest
    needs: [Build-base-cuda]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build/push Dockerfile.stempy-cuda
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          file: ./docker/Dockerfile.stempy-cuda
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stempy-cuda:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Export locally
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          file: ./docker/Dockerfile.stempy-cuda-test
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stempy-cuda-test:latest
          outputs: type=docker,dest=/tmp/stempy-cuda-test.tar

      - 
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: stempy-cuda-test
          path: /tmp/stempy-cuda-test.tar
          retention-days: 1

  # Tests stempy-cuda
  test-stempy-cuda:
    runs-on: ubuntu-latest
    needs: [Build-stempy-cuda]
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: stempy-cuda-test
          path: /tmp
      -
        name: Load image and run tests
        run: |
          docker load --input /tmp/stempy-cuda-test.tar
          docker run ${{ secrets.DOCKERHUB_USERNAME }}/stempy-cuda-test:latest /bin/bash
          conda activate stempy
          cd /test
          pytest tests